
name: 360T7

on:
  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: environment
        run: |
          sudo apt-get update
          sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'

      - name: Download
        run: |
          git clone --depth=1 https://github.com/hanwckf/immortalwrt-mt798x.git

      - name: update
        run: |
          cd immortalwrt-mt798x
          ./scripts/feeds update -a

      - name: install
        run: |
          cd immortalwrt-mt798x
          ./scripts/feeds install -a

      - name: build
        run: |
          cd immortalwrt-mt798x
          sed -i 's/192.168.1.1/192.168.2.1/g' package/base-files/files/bin/config_generate
          cp -f $GITHUB_WORKSPACE/main.config .config
          make V=s -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: 360T7
          path: immortalwrt-mt798x/bin/targets/*/*.sysupgrade.bin
