name: 360T7pw

on:
  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: environment
        run: |
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
          g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
          libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5 \
          libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lld llvm lrzsz mkisofs msmtp \
          nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip python3-ply \
          python3-docutils python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig \
          texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev g++ python3-distutils file

      - name: Download
        run: |
          git clone --depth=1 https://github.com/hanwckf/immortalwrt-mt798x.git

      - name: socket
        run: |
          cd immortalwrt-mt798x
          rm -rf ./package/network/utils/iptables/Makefile
          mv $GITHUB_WORKSPACE/Makefile package/network/utils/iptables/Makefile
          rm -rf ./package/kernel/linux/modules/netfilter.mk
          mv $GITHUB_WORKSPACE/netfilter.mk package/kernel/linux/modules/netfilter.mk

      - name: update
        run: |
          cd immortalwrt-mt798x
          ./scripts/feeds update -a

      - name: install
        run: |
          cd immortalwrt-mt798x
          ./scripts/feeds install -a

      - name: passwall
        run: |
          cd immortalwrt-mt798x
          git clone -b luci-smartdns-dev https://github.com/xiaorouji/openwrt-passwall openwrt-passwall
          rm -rf ./feeds/luci/applications/luci-app-passwall
          mv ./openwrt-passwall/luci-app-passwall ./feeds/luci/applications/luci-app-passwall
          rm -rf ./openwrt-passwall
          git clone https://github.com/xiaorouji/openwrt-passwall-packages package/openwrt-passwall-packages
          rm -rf ./package/openwrt-passwall-packages/.git && rm -rf ./package/openwrt-passwall-packages/.github && rm -rf ./package/openwrt-passwall-packages/brook && rm -rf ./package/openwrt-passwall-packages/dns2socks && rm -rf ./package/openwrt-passwall-packages/dns2tcp && rm -rf ./package/openwrt-passwall-packages/hysteria && rm -rf ./package/openwrt-passwall-packages/ipt2socks && rm -rf ./package/openwrt-passwall-packages/naiveproxy && rm -rf ./package/openwrt-passwall-packages/shadowsocks-rust && rm -rf ./package/openwrt-passwall-packages/shadowsocksr-libev && rm -rf ./package/openwrt-passwall-packages/simple-obfs && rm -rf ./package/openwrt-passwall-packages/sing-box && rm -rf ./package/openwrt-passwall-packages/trojan && rm -rf ./package/openwrt-passwall-packages/trojan-go && rm -rf ./package/openwrt-passwall-packages/trojan-plus && && rm -rf ./package/openwrt-passwall-packages/tuic-client && && rm -rf ./package/openwrt-passwall-packages/v2ray-core && && rm -rf ./package/openwrt-passwall-packages/v2ray-plugin && && rm -rf ./package/openwrt-passwall-packages/xray-core && && rm -rf ./package/openwrt-passwall-packages/xray-plugin && && rm -rf ./package/openwrt-passwall-packages/v2ray-geoip && && rm -rf ./package/openwrt-passwall-packages/v2ray-geosite

      - name: build
        run: |
          cd immortalwrt-mt798x
          sed -i 's/192.168.1.1/192.168.5.1/g' package/base-files/files/bin/config_generate
          cp -f $GITHUB_WORKSPACE/pw.config .config
          make V=s -j$(nproc)

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: |
            immortalwrt-mt798x/bin/targets/mediatek/mt7981/immortalwrt-mediatek-mt7981-mt7981-360-t7-108M-squashfs-sysupgrade.bin
            package/network/utils/iptables/Makefile
