name: 360T7pw

on:
  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: environment
        run: |
          sudo apt update -y
          sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'

      - name: Download
        run: |
          git clone --depth=1 https://github.com/hanwckf/immortalwrt-mt798x.git
          cd immortalwrt-mt798x
          sed -i 's/mt7981-fw-20230306/mt7981-fw-20230717/g' package/mtk/drivers/mt_wifi/Makefile
          sed -i 's/mt7981-fw-20230411/mt7981-fw-20230717/g' package/mtk/drivers/warp/Makefile
          sed -i 's/192.168.1.1/192.168.6.1/g' package/base-files/files/bin/config_generate
          cp -f $GITHUB_WORKSPACE/config/PWognotheme.config .config

      - name: update
        run: |
          cd immortalwrt-mt798x
          ./scripts/feeds update -a

      - name: install
        run: |
          cd immortalwrt-mt798x
          ./scripts/feeds install -a

      - name: passwall
        run: |
          cd immortalwrt-mt798x
          git clone -b main --single-branch https://github.com/xiaorouji/openwrt-passwall openwrt-passwall
          rm -rf ./feeds/luci/applications/luci-app-passwall && mv ./openwrt-passwall/luci-app-passwall ./feeds/luci/applications/luci-app-passwall && rm -rf ./openwrt-passwall
          git clone -b main --single-branch https://github.com/xiaorouji/openwrt-passwall-packages openwrt-passwall-packages
          rm -rf ./feeds/packages/net/chinadns-ng && mv ./openwrt-passwall-packages/chinadns-ng ./feeds/packages/net/chinadns-ng && rm -rf ./openwrt-passwall-packages

      - name: package
        run: |
          cd immortalwrt-mt798x
          make defconfig
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile the firmware
        run: |
          cd immortalwrt-mt798x
          make -j$(nproc) || make -j1 || make -j1 V=s

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: immortalwrt-mt798x/bin/targets/mediatek/mt7981/immortalwrt-mediatek-mt7981-mt7981-360-t7-108M-squashfs-sysupgrade.bin
