name: menuconfig24.10

on:
  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: environment
        run: sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'

      - name: Download
        run: |
          git clone -b 2410 --single-branch --filter=blob:none https://github.com/padavanonly/immortalwrt-mt798x-24.10 immortalwrt-mt798x-24.10
          cd immortalwrt-mt798x-24.10

          git clone https://github.com/xiaorouji/openwrt-passwall.git package/passwall
          git clone https://github.com/xiaorouji/openwrt-passwall-packages.git package/passwall-packages
          git clone https://github.com/openwrt/openwrt -b d6ffcdbda9c40fb35d44b0db69561c5b403f3e14 openwrt && mv ./openwrt/package/network/utils/udhcpsnoop package/network/utils/udhcpsnoop && mv ./openwrt/package/utils/ufp package/utils/ufp && rm -rf ./openwrt
          
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cp -f defconfig/mt7981-ax3000.config .config

      - name: Setup tmate session 步骤：【输入q 命令cd immortalwrt-mt798x-24.10 && make menuconfig 结束运行sudo touch /continue】 # https://github.com/mxschmitt/action-tmate https://github.com/marketplace/actions/debugging-with-ssh
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30

      - name: config
        run: |
          cd immortalwrt-mt798x-24.10
          mv .config padavanonly.config

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: config
          path: |
            immortalwrt-mt798x-24.10/padavanonly.config
            360T7/immortalwrt-mt798x-24.10/padavanonly.config
