name: menuconfig

on:
  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.24.2'
      - run: go version

      - name: environment
        run: |
         sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
         sudo docker image prune --all --force
         sudo -E apt-get -qq update
         sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison \
         build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext \
         gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev \
         libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev \
         libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp \
         ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools \
         python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo \
         uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev clang g++ libncurses-dev \
         python3-distutils file devscripts debhelper libjson-c-dev
         sudo -E apt-get -qq autoremove --purge
         sudo -E apt-get -qq clean

      - name: Download
        run: |
          git clone --depth=1 https://github.com/hanwckf/immortalwrt-mt798x.git
          cd immortalwrt-mt798x
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          sed -i 's/192.168.1.1/192.168.3.1/' package/base-files/files/bin/config_generate
          sed -i 's/ImmortalWrt/OpenWrt/' package/base-files/files/bin/config_generate
          sed -i 's/ImmortalWrt-2.4G/NW2.4G/' package/mtk/applications/mtwifi-cfg/files/mtwifi.sh
          sed -i 's/ImmortalWrt-5G/NW/' package/mtk/applications/mtwifi-cfg/files/mtwifi.sh
          sed -i 's/ImmortalWrt-6G/NW6G/' package/mtk/applications/mtwifi-cfg/files/mtwifi.sh
          sed -i 's/encryption=none/encryption=sae-mixed/' package/mtk/applications/mtwifi-cfg/files/mtwifi.sh
          sed -i '/encryption=sae-mixed/a \ \ \ \ set wireless.default_${dev}.key=blue1235' package/mtk/applications/mtwifi-cfg/files/mtwifi.sh
          git clone https://github.com/xiaorouji/openwrt-passwall.git package/passwall
          git clone https://github.com/xiaorouji/openwrt-passwall-packages.git package/passwall-packages
          rm -rf ./feeds/luci/applications/luci-app-passwall && cp -r ./package/passwall/luci-app-passwall ./feeds/luci/applications/luci-app-passwall
          rm -rf ./feeds/packages/net/chinadns-ng && cp -r ./package/passwall-packages/chinadns-ng ./feeds/packages/net/chinadns-ng
          rm -rf ./feeds/packages/net/dns2socks && cp -r ./package/passwall-packages/dns2socks ./feeds/packages/net/dns2socks
          rm -rf ./feeds/packages/net/ipt2socks && cp -r ./package/passwall-packages/ipt2socks ./feeds/packages/net/ipt2socks
          rm -rf ./feeds/packages/net/microsocks && cp -r ./package/passwall-packages/microsocks ./feeds/packages/net/microsocks
          rm -rf ./feeds/packages/net/tcping && cp -r ./package/passwall-packages/tcping ./feeds/packages/net/tcping
          rm -rf ./feeds/packages/net/sing-box && cp -r ./package/passwall-packages/sing-box ./feeds/packages/net/sing-box
          rm -rf ./feeds/packages/net/xray-core && cp -r ./package/passwall-packages/xray-core ./feeds/packages/net/xray-core
          rm -rf ./feeds/packages/net/v2ray-geodata && cp -r ./package/passwall-packages/v2ray-geodata ./feeds/packages/net/v2ray-geodata
          rm -rf ./feeds/packages/net/v2ray-plugin && cp -r ./package/passwall-packages/v2ray-plugin ./feeds/packages/net/v2ray-plugin
          rm -rf ./feeds/packages/net/hysteria && cp -r ./package/passwall-packages/hysteria ./feeds/packages/net/hysteria
          rm -rf ./feeds/packages/net/naiveproxy && cp -r ./package/passwall-packages/naiveproxy ./feeds/packages/net/naiveproxy
          rm -rf ./feeds/packages/net/shadowsocks-libev && cp -r ./package/passwall-packages/shadowsocks-libev ./feeds/packages/net/shadowsocks-libev
          rm -rf ./feeds/packages/net/shadowsocks-rust && cp -r ./package/passwall-packages/shadowsocks-rust ./feeds/packages/net/shadowsocks-rust
          rm -rf ./feeds/packages/net/shadowsocksr-libev && cp -r ./package/passwall-packages/shadowsocksr-libev ./feeds/packages/net/shadowsocksr-libev
          rm -rf ./feeds/packages/net/simple-obfs && cp -r ./package/passwall-packages/simple-obfs ./feeds/packages/net/simple-obfs
          rm -rf ./feeds/packages/net/trojan-plus && cp -r ./package/passwall-packages/trojan-plus ./feeds/packages/net/trojan-plus
          rm -rf ./feeds/packages/net/tuic-client && cp -r ./package/passwall-packages/tuic-client ./feeds/packages/net/tuic-client
          rm -rf ./feeds/packages/net/xray-plugin && cp -r ./package/passwall-packages/xray-plugin ./feeds/packages/net/xray-plugin
          cp -r ./package/passwall-packages/geoview ./feeds/packages/net/geoview
          git clone https://github.com/immortalwrt/packages.git immortalwrt-packages && rm -rf ./feeds/packages/lang/golang && mv ./immortalwrt-packages/lang/golang feeds/packages/lang/golang && rm -rf ./immortalwrt-packages
          cp -f defconfig/mt7981-ax3000.config .config

      - name: Setup tmate session 步骤：【输入q 命令cd immortalwrt-mt798x && make menuconfig 结束运行sudo touch /continue】 # https://github.com/mxschmitt/action-tmate https://github.com/marketplace/actions/debugging-with-ssh
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30

      - name: config
        run: |
          cd immortalwrt-mt798x
          mv .config hanwckf.config

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: config
          path: |
            immortalwrt-mt798x/hanwckf.config
            360T7/immortalwrt-mt798x/hanwckf.config
