name: menuconfig

on:
  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: environment
        run: sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'

      - name: Download
        run: |
          git clone --depth=1 https://github.com/hanwckf/immortalwrt-mt798x.git
          #git clone -b 2410 --single-branch --filter=blob:none https://github.com/padavanonly/immortalwrt-mt798x-24.10 immortalwrt-mt798x-24.10
          cd immortalwrt-mt798x
          #cd immortalwrt-mt798x-24.10

          git clone https://github.com/xiaorouji/openwrt-passwall.git package/passwall
          git clone https://github.com/xiaorouji/openwrt-passwall-packages.git package/passwall-packages
          #echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall.git;main" >> "feeds.conf.default"
          #echo "src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git;main" >> "feeds.conf.default"
          git clone https://github.com/XGHeaven/homebox package/homebox
          git clone https://github.com/selfcan/luci-app-homebox package/luci-app-homebox
          #echo "src-git homebox https://github.com/XGHeaven/homebox.git;master" >> "feeds.conf.default"
          #echo "src-git luci-app-homebox https://github.com/selfcan/luci-app-homebox.git;main" >> "feeds.conf.default"
          
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cp -f defconfig/mt7981-ax3000.config .config

          #git clone -b main --single-branch https://github.com/xiaorouji/openwrt-passwall openwrt-passwall
          #rm -rf ./feeds/luci/applications/luci-app-passwall && mv ./openwrt-passwall/luci-app-passwall ./feeds/luci/applications/luci-app-passwall && rm -rf ./openwrt-passwall
          #git clone -b main --single-branch https://github.com/xiaorouji/openwrt-passwall-packages openwrt-passwall-packages
          #rm -rf ./feeds/packages/net/chinadns-ng && mv ./openwrt-passwall-packages/chinadns-ng ./feeds/packages/net/chinadns-ng && rm -rf ./openwrt-passwall-packages

      - name: Setup tmate session 步骤：【输入q 命令cd immortalwrt-mt798x && make menuconfig 结束运行sudo touch /continue】 # https://github.com/mxschmitt/action-tmate https://github.com/marketplace/actions/debugging-with-ssh
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30

      - name: config
        run: |
          cd immortalwrt-mt798x
          #cd immortalwrt-mt798x-24.10
          mv .config hanwckf.config

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: config
          path: |
            immortalwrt-mt798x/hanwckf.config
            360T7/immortalwrt-mt798x/hanwckf.config
            #immortalwrt-mt798x-24.10/padavanonly.config
            #360T7/immortalwrt-mt798x-24.10/padavanonly.config
